src/Entity/Covoiturage.php
<?php

namespace App\Entity;

use App\Repository\CovoiturageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CovoiturageRepository::class)]
class Covoiturage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_depart = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heure_depart = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_depart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_arrivee = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heure_arrivee = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_arrivee = null;

    #[ORM\Column(length: 50)]
    private ?string $statut = null;

    #[ORM\Column]
    private ?int $nb_place = null;

    #[ORM\Column]
    private ?float $prix_personne = null;

    #[ORM\ManyToOne(inversedBy: 'covoiturages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Voiture $voiture = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'covoiturages')]
    private Collection $users;

    #[ORM\Column(nullable: true)]
    private ?int $duree = null;


    public function __construct()
    {
        $this->users = new ArrayCollection();
    
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDepart(): ?\DateTime
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTime $date_depart): static
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getHeureDepart(): ?\DateTime
    {
        return $this->heure_depart;
    }

    public function setHeureDepart(\DateTime $heure_depart): static
    {
        $this->heure_depart = $heure_depart;

        return $this;
    }

    public function getLieuDepart(): ?string
    {
        return $this->lieu_depart;
    }

    public function setLieuDepart(string $lieu_depart): static
    {
        $this->lieu_depart = $lieu_depart;

        return $this;
    }

    public function getDateArrivee(): ?\DateTime
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTime $date_arrivee): static
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getHeureArrivee(): ?\DateTime
    {
        return $this->heure_arrivee;
    }

    public function setHeureArrivee(\DateTime $heure_arrivee): static
    {
        $this->heure_arrivee = $heure_arrivee;

        return $this;
    }

    public function getLieuArrivee(): ?string
    {
        return $this->lieu_arrivee;
    }

    public function setLieuArrivee(string $lieu_arrivee): static
    {
        $this->lieu_arrivee = $lieu_arrivee;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): static
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getPrixPersonne(): ?float
    {
        return $this->prix_personne;
    }

    public function setPrixPersonne(float $prix_personne): static
    {
        $this->prix_personne = $prix_personne;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): static
    {
        $this->voiture = $voiture;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addCovoiturage($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeCovoiturage($this);
        }

        return $this;
    }

 

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): static
    {
        $this->duree = $duree;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 20)]
    private ?string $telephone = null;

    #[ORM\Column(length: 50)]
    private ?string $adresse = null;

    #[ORM\Column(length: 50)]
    private ?string $date_de_naissance = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo = null;

    #[ORM\Column]
    private ?int $credit = null;

    /**
     * @var Collection<int, Voiture>
     */
    #[ORM\OneToMany(targetEntity: Voiture::class, mappedBy: 'user')]
    private Collection $voitures;

    /**
     * @var Collection<int, Configuration>
     */
    #[ORM\OneToMany(targetEntity: Configuration::class, mappedBy: 'user')]
    private Collection $configurations;

    /**
     * @var Collection<int, Covoiturage>
     */
    #[ORM\ManyToMany(targetEntity: Covoiturage::class, inversedBy: 'user')]
    private Collection $covoiturages;

   

    /**
     * @var Collection<int, Avis>
     */
    #[ORM\ManyToMany(targetEntity: Avis::class, inversedBy: 'user')]
    private Collection $avis;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isSuspended = null;

    public function __construct()
    {
        $this->voitures = new ArrayCollection();
        $this->configurations = new ArrayCollection();
        $this->covoiturages = new ArrayCollection();
        $this->avis = new ArrayCollection();
    }

    
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDateDeNaissance(): ?string
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(string $date_de_naissance): static
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getCredit(): ?int
    {
        return $this->credit;
    }

    public function setCredit(int $credit): static
    {
        $this->credit = $credit;

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): static
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures->add($voiture);
            $voiture->setUser($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): static
    {
        if ($this->voitures->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getUser() === $this) {
                $voiture->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Configuration>
     */
    public function getConfigurations(): Collection
    {
        return $this->configurations;
    }

    public function addConfiguration(Configuration $configuration): static
    {
        if (!$this->configurations->contains($configuration)) {
            $this->configurations->add($configuration);
            $configuration->setUser($this);
        }

        return $this;
    }

    public function removeConfiguration(Configuration $configuration): static
    {
        if ($this->configurations->removeElement($configuration)) {
            // set the owning side to null (unless already changed)
            if ($configuration->getUser() === $this) {
                $configuration->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Covoiturage>
     */
    public function getCovoiturages(): Collection
    {
        return $this->covoiturages;
    }

    public function addCovoiturage(Covoiturage $covoiturage): static
    {
        if (!$this->covoiturages->contains($covoiturage)) {
            $this->covoiturages->add($covoiturage);
            $covoiturage->addUser($this);
        }

        return $this;
    }

    public function removeCovoiturage(Covoiturage $covoiturage): static
    {
        if ($this->covoiturages->removeElement($covoiturage)) {
            $covoiturage->removeUser($this);
        }

        return $this;
    }

   
    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        $this->avis->removeElement($avi);

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    //calcul note moyenne pour l'afficher sur covoiturage/index.html.twig

    public function getNoteMoyenne(): float
    {
    $avisRecus = $this->getAvis(); 

    if ($avisRecus->isEmpty()) {
        return 0.0;
    }

    $total = 0;
    $count = 0;

    foreach ($avisRecus as $avi) {
        // On ne prend que les avis validés
        if ($avi->getStatut() === 'validé') {
            // (int) convertit ta chaîne "5" en nombre 5 pour le calcul
            $total += (int)$avi->getNote();
            $count++;
        }
    }

    if ($count === 0) return 0.0;

    return round($total / $count, 1);
}

    public function isSuspended(): ?bool
    {
        return $this->isSuspended;
    }

    public function setIsSuspended(?bool $isSuspended): static
    {
        $this->isSuspended = $isSuspended;

        return $this;
    }



}

src/Form/CovoiturageType.php
<?php

namespace App\Form;

use App\Entity\Covoiturage;
use App\Entity\Voiture; // Ne pas oublier de décommenter
use App\Entity\Marque;  // Utile si tu veux un label précis
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;

class CovoiturageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // On récupère l'utilisateur passé dans les options
        $user = $options['user'];

        $builder
            ->add('date_depart', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Jour de départ'
            ])
            ->add('heure_depart', TimeType::class, [
                'widget' => 'single_text',
                'label' => 'Heure de Départ'
            ])
            ->add('lieu_depart', TextType::class, [
                'label' => 'Adresse de départ',
                'attr' => [
                    'placeholder' => 'Saisissez une adresse précise...',
                    'class' => 'adresse-autocomplete'
                ]
            ])
            ->add('date_arrivee', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Jour d\'arrivée'
            ])
            ->add('heure_arrivee', TimeType::class, [
                'widget' => 'single_text',
                'label' => 'Heure d\'arrivée'
            ])
            ->add('lieu_arrivee', TextType::class, [
                'label' => 'Adresse de destination',
                'attr' => [
                    'placeholder' => 'Saisissez une adresse de destination...',
                    'class' => 'adresse-autocomplete'
                ]
            ])
            ->add('prix_personne', MoneyType::class, [
                'label' => 'Prix (Crédits)',
                'currency' => 'EUR'
            ])
            // --- AJOUT DU CHOIX DU VÉHICULE ---
            ->add('voiture', EntityType::class, [
                'class' => Voiture::class,
                'label' => 'Véhicule utilisé',
                'placeholder' => 'Choisissez votre véhicule',
                // On affiche la marque et le modèle dans la liste
                'choice_label' => function (Voiture $voiture) {
                    return $voiture->getMarque()->getLibelle() . ' ' . $voiture->getModele() . ' (' . $voiture->getImmatriculation() . ')';
                },
                // REQUÊTE POUR FILTRER : Uniquement les voitures de l'utilisateur connecté
                'query_builder' => function (EntityRepository $er) use ($user) {
                    return $er->createQueryBuilder('v')
                        ->where('v.user = :u')
                        ->setParameter('u', $user);
                },
            ]);

            // Note : On retire nb_place du formulaire car il sera 
            // rempli automatiquement par la capacité du véhicule choisi dans le contrôleur.
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Covoiturage::class,
            'user' => null, // On déclare l'option "user" pour pouvoir l'utiliser
        ]);
    }
}

templates/covoiturage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EcoRide - Rechercher un trajet{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="mb-4 text-success">Trajets disponibles</h1>

   {# On réutilise le bloc du home #}
<div class="card shadow p-4 border-0 mb-5">
    {{ form_start(searchForm, {'action': path('app_covoiturage_index'), 'method': 'GET'}) }}
        <div class="row g-3">
            <div class="col-md-4">{{ form_widget(searchForm.depart) }}</div>
            <div class="col-md-4">{{ form_widget(searchForm.arrivee) }}</div>
            <div class="col-md-3">{{ form_widget(searchForm.date) }}</div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-success w-100"><i class="bi bi-search"></i></button>
            </div>
        </div>

        <div class="text-start mt-3">
            <button class="btn btn-link text-success p-0 text-decoration-none" type="button" data-bs-toggle="collapse" data-bs-target="#extraFilters">
                <i class="bi bi-plus-circle"></i> Plus de filtres
            </button>
        </div>

        <div class="collapse mt-3" id="extraFilters">
            <div class="row g-3 border-top pt-3">
                <div class="col-md-4">{{ form_row(searchForm.prixMax) }}</div>
                <div class="col-md-4">{{ form_row(searchForm.dureeMax) }}</div>
                <div class="col-md-4">{{ form_row(searchForm.noteMin) }}</div>
                <div class="col-12 text-center mt-2">
                    {{ form_widget(searchForm.estEcologique) }} {{ form_label(searchForm.estEcologique) }}
                </div>
            </div>
        </div>
    {{ form_end(searchForm, {'render_rest': false}) }}
</div>



<div class="row">
    {% for trajet in trajets %}
        {% set chauffeur = trajet.voiture.user %} {# On récupère le propriétaire de la voiture #}
        
    <div class="col-12 mb-4">
        <div class="card shadow-sm trajet-card">
            <div class="card-body">
                <div class="row align-items-center">
                
                {# INFOS CHAUFFEUR #}
                    <div class="col-md-3 text-center border-end">
                        <img src="{{ chauffeur.photo|default('https://ui-avatars.com/api/?name=' ~ chauffeur.pseudo) }}" 
                         class="driver-thumb" 
                         alt="Photo de {{ chauffeur.pseudo }}">
                    <h6 class="driver-name">{{ chauffeur.pseudo }}</h6>
                {# Affichage de la note (tu peux adapter selon ta fonction de calcul) #}
                    <div class="text-warning small">
                        <i class="bi bi-star-fill"></i> 
                        {{ chauffeur.noteMoyenne }}/5
                    </div>
                    </div>
                {# INFOS TRAJET (Heures, Dates, Écologie) #}
                    <div class="col-md-6 px-4">
                        <div class="d-flex justify-content-between mb-2">
                            <div class="text-start">
                                <span class="badge bg-light text-dark">{{ trajet.heureDepart|date('H:i') }}</span>
                                <span class="badge bg-light text-dark">{{ trajet.dateDepart|date('d/m/Y') }}</span>                
                                    <p class="text-muted small">{{ trajet.lieuDepart }}</p>
                             </div>
                                <div class="align-self-center text-success">
                                    <i class="bi bi-arrow-right fs-4"></i>
                                </div>
                            <div class="text-end">
                                <span class="badge bg-light text-dark">{{ trajet.heureArrivee|date('H:i') }}</span>
                                <span class="badge bg-light text-dark">{{ trajet.dateArrivee|date('d/m/Y') }}</span>                                  
                                    <p class="text-muted small">{{ trajet.lieuArrivee }}</p>
                            </div>
                        </div>

                {# MENTION ÉCOLOGIQUE #}
                    <div class="mt-2">
                        {% if 'electrique' in trajet.voiture.energie|lower|replace({'é': 'e'}) %}
                            <span class="badge bg-success p-2">
                            <i class="bi bi-leaf-fill"></i> Voyage écologique
                            </span>
                                 <small class="text-success d-block mt-1">Ce trajet émet 0g de CO2 durant la conduite.</small>
                        {% else %}
                            <span class="badge bg-secondary-subtle text-muted p-2">
                                  Standard ({{ trajet.voiture.energie }})
                            </span>
                        {% endif %}
                    </div>
                    </div>

                {# PRIX, PLACES & BOUTON DÉTAIL #}
                    <div class="col-md-3 text-end">
                        <h3 class="text-success fw-bold mb-0">{{ trajet.prixPersonne }} €</h3>
                        <p class="text-muted small mb-3">{{ trajet.nbPlace }} places restantes</p>
                            <a href="{{ path('app_covoiturage_show', {'id': trajet.id}) }}" class="btn btn-success w-100">
                                <i class="bi bi-eye"></i> Détails
                            </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
   
    {% endfor %}
</div>
{% endblock %}

templates/covoiturage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du trajet - EcoRide{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        {# Colonne Gauche : Infos Trajet #}
        <div class="col-md-8">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <h2 class="text-success mb-4 border-bottom pb-2">
                        {{ covoiturage.lieuDepart }} → {{ covoiturage.lieuArrivee }}
                    </h2>
                    
                    <div class="row mb-4">
                        <div class="col-6">
                            <p class="mb-1 text-muted">DÉPART</p>
                            <p class="h5"><strong>{{ covoiturage.dateDepart|date('d/m/Y') }}</strong></p>
                            <p class="h5 text-success fw-bold">{{ covoiturage.heureDepart|date('H:i') }}</p>
                        </div>
                        <div class="col-6 text-end">
                            <p class="mb-1 text-muted">PRIX</p>
                            <p class="h3 text-success"><strong>{{ covoiturage.prixPersonne }} Crédits</strong></p>
                        </div>
                    </div>

                    <div class="alert alert-info">
                        <strong>Véhicule :</strong> {{ covoiturage.voiture.marque.libelle }} {{ covoiturage.voiture.modele }} <br>
                        <strong>Énergie :</strong> {{ covoiturage.voiture.energie }}
                    </div>
                </div>
            </div>
        </div>
{# Colonne Droite : Action & Places #}
        <div class="col-md-4">
            <div class="card shadow-sm border-success">
                <div class="card-body text-center">
                    <p class="h4 mb-3">{{ covoiturage.nbPlace }} places disponibles</p>
                    
                    {% if app.user %}
    {# Bouton déclencheur de la modale #}
    <button type="button" class="btn btn-success btn-lg w-100 mb-2" data-bs-toggle="modal" data-bs-target="#confirmReservationModal">
        Participer
    </button>

    <a href="{{ path('app_avis_new', {id: covoiturage.id}) }}" class="btn btn-primary w-100">
        Donner mon avis sur ce trajet
    </a>
{% else %}
    <a href="{{ path('app_login') }}" class="btn btn-outline-secondary w-100">Connectez-vous pour réserver</a>
{% endif %}
{# La Modale de Confirmation #}
<div class="modal fade" id="confirmReservationModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel">Confirmer votre participation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Souhaitez-vous confirmer votre réservation pour ce trajet ?</p>
                <div class="alert alert-warning">
                    <i class="bi bi-info-circle me-2"></i>
                    <strong>Coût du trajet :</strong> {{ covoiturage.prixPersonne }} crédits.
                </div>
                <p class="small text-muted">Votre solde actuel : {{ app.user.credit }} €</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <a href="{{ path('app_covoiturage_reserve', {'id': covoiturage.id}) }}" class="btn btn-success px-4">
                    Confirmer et utiliser mes crédits
                </a>
            </div>
        </div>
    </div>
</div>
                    
                    <a href="{{ path('app_covoiturage_index') }}" class="btn btn-link mt-3 text-muted">Retour à la liste</a>
                </div>
            </div>
        </div>

        {# --- SECTION PRÉFÉRENCES DANS VOITURE --- #}
<div class="mt-4">
    <h4 class="h5 border-bottom pb-2">Préférences</h4>
    <div class="row mt-3">
        {# Préférence Fumeur #}
        <div class="col-6 col-md-4">
            <div class="d-flex align-items-center mb-3">
                {% if covoiturage.voiture.fumeur %}
                    <i class="bi bi-check-circle-fill text-success me-2 fs-4"></i>
                    <span>Fumeurs autorisés</span>
                {% else %}
                    <i class="bi bi-x-circle-fill text-danger me-2 fs-4"></i>
                    <span>pas de fumeurs</span>
                {% endif %}
            </div>
        </div>
        

        {# Préférence Animaux #}
        <div class="col-6 col-md-4">
            <div class="d-flex align-items-center mb-3">
                {% if covoiturage.voiture.animaux %}
                    <i class="bi bi-check-circle-fill text-success me-2 fs-4"></i>
                    <span>Animaux autorisés</span>
                {% else %}
                    <i class="bi bi-x-circle-fill text-danger me-2 fs-4"></i>
                    <span>Pas d'animaux</span>
                {% endif %}
            </div>
        </div>
    </div>
</div>

        {# --- AVIS DU CONDUCTEUR --- #}
        <div class="mt-5">
            <h4 class="h5 border-bottom pb-2">Derniers avis sur {{ covoiturage.voiture.user.pseudo }}</h4>
        {% for avis in covoiturage.voiture.user.avis %}
                <div class="mb-3 p-3 bg-light rounded shadow-sm">
                    <div class="d-flex justify-content-between align-items-center">
                        <span class="fw-bold text-warning">
                            {% for i in 1..5 %}
                                <i class="bi bi-star{{ i <= avis.note ? '-fill' : '' }}"></i>
                            {% endfor %}
                        </span>
                    </div>
                        <p class="mb-0 mt-2 italic">"{{ avis.commentaire }}"</p>
                </div>
        {% else %}
            <p class="text-muted small">Aucun avis n'a été laissé pour ce conducteur.</p>
        {% endfor %}
                    </div>
                </div>
        </div>
    </div>

        
{% endblock %}